CHANGES MADE
CodeChefVIT/whatsapp-groupadd pull request #1
Opened 2019-12-25 19:42 UTC by bhaveshgoyal27

2019-12-25 22:52 UTC, YashMeh approved these changes

2019-12-25 22:58 UTC, YashMeh commented on README.md
> +Clone the repo and in the edit the people.csv in the Samples folder as your need
Grammatical error.

2019-12-25 23:03 UTC, YashMeh requested changes
Instead of asking the user to make changes directly to the script- 
- Ask for user input when user launches index.py.
- Convert the whatsapp_group.py code into a single function call.
- Pass those parameters to the function.

2019-12-26 06:26 UTC, vinitshahdeo commented on README.md
> +
Mention `requirements` too. 
It's good to have pre-requisites before Installation steps.

2019-12-26 06:26 UTC, vinitshahdeo commented on README.md
> +
Do we also have tests?

2019-12-26 06:26 UTC, vinitshahdeo commented on README.md
> +
**WhatsApp** is a proper noun. It should be capitalized always.
Also, it looks odd when you write _whatsapp, Whatsapp_ etc.

- WhatsApp :white_check_mark:
- whatsapp ❌ 
- Whatsapp ❌

2019-12-26 17:16 UTC, closed without merging